[tool.poetry]
name = "repr-preference-optimization"
version = "0.1.0"
description = ""
authors = ["wassname <github@wassname.org>"]
readme = "README.md"
repository = "https://github.com/wassname/repr-preference-optimization"

[tool.poetry.dependencies]
python = "^3.9"
ipykernel = "^6.29.5"
numpy = "^2.0.0"
torch = "2.0.1"
tqdm = "^4.66.4"
transformers = "4.29.2"
datasets = "2.12.0"
wandb = "^0.17.4"
tensor-parallel = "1.2.4"
hydra-core = "1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
