[tool.poetry]
name = "reprpo"
version = "0.1.0"
description = ""
authors = ["wassname <github@wassname.org>"]
readme = "README.md"
repository = "https://github.com/wassname/repr-preference-optimization"

[virtualenvs]
in-project = true

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
tqdm = "^4.66.4"
transformers = "^4.43.2"
datasets = "^2.20.0"
tensor-parallel = "^1.2.4"
#hydra-core = "^1.3.2"
#torch = "2.0.1"
torch = { version = ">=2.3.1+cu121", source = "pytorch" }
ipywidgets = "^8.1.3"
beautifulsoup4 = "^4.12.3"
trl = "^0.9.4"
bitsandbytes = "0.43.1"
accelerate = "0.32.1"
loralib = "^0.1.2"
einops = "^0.8.0"
jaxtyping = "^0.2.19"
setuptools = "^70.2.0"
tensorboardx = "^2.6.2.2"
matplotlib = "^3.9.1"
peft = "^0.12.0"
wandb = "^0.17.4"
tabulate = "^0.9.0"
jinja2 = "^3.1.4"
pyarrow = "^17.0.0"
scikit-learn = "^1.5.1"
sympy = "^1.13.1"
statsmodels = "^0.14.2"
baukit = { git = "https://github.com/wassname/baukit.git" }
loguru = "^0.7.2"
# https://github.com/wassname/open_pref_eval
# open-pref-eval = {path = "/media/wassname/SGIronWolf/projects5/elk/open_pref_eval", develop = true}
open-pref-eval = { git = "https://github.com/wassname/open_pref_eval", branch = "main", develop = true }
lightning = "^2.4.0"
# simple-parsing = "^0.1.5"
tyro = "^0.8.10"
colorama = "^0.4.6"
ax-platform = "^0.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
ruff = "^0.1.3"
pylama = "^8.4.1"
pytest = "^8.3.3"
pytest-beartype = "^0.1.0"

[tool.pytest.ini_options]
addopts = "--jaxtyping-packages=reprpo,beartype.beartype --beartype-packages='reprpo'"
# beartype-packages = "reprpo,jaxtyping"
# jaxtyping-packages = "reprpo,beartype.beartype"
# durations=0
