[tool.poetry]
name = "repr-preference-optimization"
version = "0.1.0"
description = ""
authors = ["wassname <github@wassname.org>"]
readme = "README.md"
repository = "https://github.com/wassname/repr-preference-optimization"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^2.0.0"
tqdm = "^4.66.4"
transformers = "4.29.2"
datasets = "2.12.0"
wandb = "^0.17.4"
tensor-parallel = "1.2.4"
hydra-core = "1.3.2"
#torch = "2.0.1"
torch = {version = "^2.0.1+cu121", source = "pytorch"}
ipywidgets = "^8.1.3"
beautifulsoup4 = "^4.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
ruff = "^0.1.3"
pylama = "^8.4.1"
