[tool.poetry]
name = "reprpo"
version = "0.1.0"
description = ""
authors = ["wassname <github@wassname.org>"]
readme = "README.md"
repository = "https://github.com/wassname/repr-preference-optimization"

[tool.poetry.dependencies]
python = "^3.9"
tqdm = "^4.66.4"
transformers = "^4.42.4"
datasets = "^2.12.0"
tensor-parallel = "^1.2.4"
hydra-core = "^1.3.2"
#torch = "2.0.1"
torch = {version = "^2.0.1+cu121", source = "pytorch"}
ipywidgets = "^8.1.3"
beautifulsoup4 = "^4.12.3"
trl = "^0.9.4"
bitsandbytes = "^0.43.1"
accelerate = "^0.32.1"
loralib = "^0.1.2"
einops = "^0.8.0"
jaxtyping = "^0.2.31"
setuptools = "^70.2.0"
tensorboardx = "^2.6.2.2"
matplotlib = "^3.9.1"
peft = {git = "https://github.com/huggingface/peft.git"}
wandb = "^0.17.4"
tabulate = "^0.9.0"
jinja2 = "^3.1.4"
ninja = "^1.11.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
ruff = "^0.1.3"
pylama = "^8.4.1"
