base_model: 'yujiepan/llama-3.1-tiny-random' # 1M
# base_model: HuggingFaceTB/SmolLM-135M-Instruct
n_samples: 64
eval_samples: 32 # 10 mins to go through 750*4
collection_layers_side: 
  - 0
dev: true
verbose: 2
