base_model: 'reciprocate/tiny-llama' # 1M
# base_model: 'roneneldan/TinyStories-1M' $ fail weird layer names
# base_model: HuggingFaceTB/SmolLM-135M
n_samples: 64
eval_samples: 32 # 10 mins to go through 750*4
collection_layers_side: 
  - 0
dev: true
verbose: 2
